# Generated by Django 4.1.4 on 2023-02-05 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_topic_room_host_message_room_tpic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='tpic',
            new_name='topic',
        ),
    ]
